name: Extract Image Tag from Docker Hub
description: "Fetches the latest Docker image tag (short SHA) from Docker Hub"

inputs:
  image-repo:
    description: "Docker image repository (e.g., ozblech/receipts-api)"
    required: true

outputs:
  current_image_sha:
    description: "Current image tag (e.g., a1b2c3d)"
    value: ${{ steps.extract.outputs.current_image_sha }}

runs:
  using: "composite"
  steps:
    - name: Fetch latest Docker tag (short SHA) from Docker Hub
      id: fetch-latest-tag
      shell: bash
      run: |
        set -e
        IMAGE_REPO="${{ inputs.image-repo }}"
        echo "Fetching tags for $IMAGE_REPO from Docker Hub..."

        RAW_JSON=$(curl -s "https://registry.hub.docker.com/v2/repositories/${IMAGE_REPO}/tags?page_size=100")
        echo "RAW JSON from Docker Hub:"
        echo "$RAW_JSON"

        echo "$RAW_JSON" | jq -r '.results[].name'

        TAG=$(echo "$RAW_JSON" \
          | jq -r '.results[].name' \
          | grep -E '^[a-f0-9]{7}$' \
          | sort -r \
          | head -n1)

        if [[ -z "$TAG" ]]; then
          echo "❌ No tag matched the short SHA pattern. Exiting."
          exit 1
        fi

        echo "✅ Latest short SHA tag is: $TAG"
        echo "current_image_sha=$TAG" >> "$GITHUB_OUTPUT"