# k8s/secret-template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: receipts-secret
type: Opaque
stringData:
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
  S3_REGION: "${S3_REGION}"
  DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
