apiVersion: v1
kind: Secret
metadata:
  name: receipts-secrets
type: Opaque
data:
  DB_USER: {{ .Values.secret.db_user | quote }}
  DB_PASSWORD: {{ .Values.secret.db_password | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.AWS_SECRET_ACCESS_KEY | quote }}
stringData:
  S3_BUCKET_NAME: {{ .Values.secret.s3_bucket_name | quote }}
  S3_REGION: {{ .Values.secret.s3_region | quote }}
  DB_CONNECTION_STRING: {{ .Values.secret.db_connection_string | quote }}
