{{- $secret := .Values.secret | default dict }}
{{- $aws := .Values.aws | default dict }}
{{- if and $secret.db_user $secret.db_password $aws.AWS_ACCESS_KEY_ID $aws.AWS_SECRET_ACCESS_KEY $secret.s3_bucket_name $secret.s3_region $secret.db_connection_string }}
apiVersion: v1
kind: Secret
metadata:
  name: receipts-secrets
type: Opaque
data:
  DB_USER: {{ $secret.db_user | quote }}
  DB_PASSWORD: {{ $secret.db_password | quote }}
  AWS_ACCESS_KEY_ID: {{ $aws.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $aws.AWS_SECRET_ACCESS_KEY | quote }}
stringData:
  S3_BUCKET_NAME: {{ $secret.s3_bucket_name | quote }}
  S3_REGION: {{ $secret.s3_region | quote }}
  DB_CONNECTION_STRING: {{ $secret.db_connection_string | quote }}
{{- end }}
