name: Extract Image Tag
description: "Generates Docker image tag from latest Git tag and short SHA"

outputs:
  new_image_tag:
    description: "Generated image tag (e.g., 1.0.15-a1b2c3d)"
    value: ${{ steps.extract.outputs.new_image_tag }}
  new_version:
    description: "Next version in X.Y.Z format (e.g., 1.0.15)"
    value: ${{ steps.extract.outputs.new_version }}
  current_image_tag:
    description: "Current image tag without 'v' prefix (e.g., 1.0.14-a1b2c3d)"
    value: ${{ steps.extract.outputs.current_image_tag }}
  previous_image_tag:
    description: "Previous image tag (e.g., 1.0.13-a1b2c3d)"
    value: ${{ steps.extract.outputs.previous_image_tag }}
  previous_version:
    description: "Previous version with 'v' prefix (e.g., v1.0.13)"
    value: ${{ steps.extract.outputs.previous_version }}

runs:
  using: "composite"
  steps:
    - name: Extract Git tag and SHA
      id: extract
      shell: bash
      # run: |
      #   git fetch --tags
      #   TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v1.0.0")
      #   SHORT_SHA=$(git rev-parse --short HEAD)
      #   CLEAN_TAG="${TAG#v}"
      #   echo "current_image_tag=${CLEAN_TAG}-${SHORT_SHA}" >> $GITHUB_OUTPUT
      #   IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_TAG"
      #   NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
      #   echo "new_image_tag=${NEW_VERSION}-${SHORT_SHA}" >> $GITHUB_OUTPUT
      #   echo "new_version=v${NEW_VERSION}" >> $GITHUB_OUTPUT
      run: |
        git fetch --tags

        # Get the two most recent tags (sorted by creation date)
        TAGS=$(git tag --sort=-creatordate | grep '^v' | head -n 2)
        TAG=$(echo "$TAGS" | sed -n '1p')
        PREV_TAG=$(echo "$TAGS" | sed -n '2p')

        # If no tags exist, default
        TAG=${TAG:-v1.0.0}
        PREV_TAG=${PREV_TAG:-v1.0.0}

        # Short SHA of current commit
        SHORT_SHA=$(git rev-parse --short HEAD)

        # Short SHA of previous commit
        PREV_SHORT_SHA=$(git rev-parse --short "$PREV_TAG")

        # Strip 'v' prefix
        CLEAN_TAG="${TAG#v}"
        CLEAN_PREV_TAG="${PREV_TAG#v}"

        # Create image tag based on current tag + SHA
        echo "current_image_tag=${CLEAN_TAG}-${SHORT_SHA}" >> $GITHUB_OUTPUT

        # Bump patch version
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_TAG"
        NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
        echo "new_image_tag=${NEW_VERSION}-${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "new_version=v${NEW_VERSION}" >> $GITHUB_OUTPUT

        # Output previous image tag
        echo "previous_image_tag=${CLEAN_PREV_TAG}-${PREV_SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "previous_version=${PREV_TAG}" >> $GITHUB_OUTPUT