name: Run-SSM-Command
description: "Runs a command on an EC2 instance using AWS SSM."

inputs:
  aws_account_id:
    description: "AWS Account ID to construct the role ARN"
    required: true
  instance_id:
    description: "The ID of the EC2 instance to run the command on"
  commands:
    description: "The command to run on the EC2 instance"
    required: true
outputs:
  command_output:
    description: "Output of the command execution"
    value: ${{ steps.run-ssm-command.outputs.command_output }}
  command_id:
    description: "The ID of the command that was run"
    value: ${{ steps.run-ssm-command.outputs.command_id }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials (via OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: "arn:aws:iam::${{ inputs.aws_account_id }}:role/github-actions-role"
        aws-region: us-west-2

    - name: Run command on EC2 instance
      shell: bash
      run: |
        set -euo pipefail
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids ${{ inputs.instance_id }} \
          --document-name "AWS-RunShellScript" \
          --comment "Running command on EC2 instance" \
          --parameters '{"commands": ${{ inputs.commands }}}' \
          --region us-west-2 \
          --query "Command.CommandId" \
          --output text)

          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ inputs.instance_id }} \
            --region us-west-2

          OUTPUT=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id ${{ inputs.instance_id }} \
            --query 'StandardOutputContent' \
            --output text)

          echo "command_output=$OUTPUT" >> $GITHUB_OUTPUT
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
          echo "Command executed successfully. Output: $OUTPUT"
          echo "Command ID: $COMMAND_ID"
          