name: Run-SSM-Command
description: "Runs a command on an EC2 instance using AWS SSM."

inputs:
  aws_account_id:
    description: "AWS Account ID to construct the role ARN"
    required: true
  instance_id:
    description: "The ID of the EC2 instance to run the command on"
    required: true
  commands-file-name:
    description: "The command to run on the EC2 instance (in JSON format file) "
    required: true
  aws_region:
    description: "AWS region where the EC2 instance is located"
    required: true
outputs:
  command_output:
    description: "Output of the command execution"
    value: ${{ steps.run-ssm-command.outputs.command_output }}
  command_id:
    description: "The ID of the command that was run"
    value: ${{ steps.run-ssm-command.outputs.command_id }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials (via OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: "arn:aws:iam::${{ inputs.aws_account_id }}:role/github-actions-role"
        aws-region: ${{ inputs.aws_region }}

    - name: Run command on EC2 instance
      id: run-ssm-command
      shell: bash
      env:
        INSTANCE_ID: ${{ inputs.instance_id }}
        AWS_REGION: ${{ inputs.aws_region }}
      run: |
        set -euo pipefail
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids ${{ inputs.instance_id }} \
          --document-name "AWS-RunShellScript" \
          --comment "Running command on EC2 instance" \
          --parameters file://${{ inputs.commands-file-name }} \
          --region $AWS_REGION \
          --query "Command.CommandId" \
          --output text)

          echo "Waiting for command to complete..."
          aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id "$INSTANCE_ID" \
          --region "$AWS_REGION" \
          --timeout 600
          
          echo "Fetching command output..."
          COMMAND_OUTPUT=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --region "$AWS_REGION" \
            --query "StandardOutputContent" \
            --output text)

          echo "---- RAW OUTPUT ----"
          echo "::add-mask::$COMMAND_OUTPUT"
          echo "--------------------"
          echo "command_output<<EOF" >> "$GITHUB_OUTPUT"
          echo "::add-mask::$COMMAND_OUTPUT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          echo "command_id=$COMMAND_ID" >> "$GITHUB_OUTPUT"