name: CI - Docker Build & Push

on:
  pull_request:
    branches: [dev, main]

    paths:
      - 'receipts_project/**'

jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./receipts_project
          file: ./receipts_project/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/receipts-api:latest
