name: Unit test

on:
  pull_request:
    branches: [dev, main]
    paths:
      - 'receipts_project/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r receipts_project/requirements.txt

      - name: Run unit tests
        run: |
          pytest receipts_project/tests --maxfail=1 --disable-warnings -q
  